name: Workflow Linter
on: push

jobs:
  linter:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
      - run: go version
      - run: golangci-lint
